// backups/frontend-react/src/app/(authenticated)/chat/page.tsx
'use client';

import { useState, useRef, useEffect } from 'react';
import { createSSEConnection } from '@/lib/api/sse';
import { useAuthStore } from '@/store/auth.store';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Send, Loader2 } from 'lucide-react';
import { ChatMessage } from '@/components/chat/ChatMessage';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  isStreaming?: boolean;
}

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const currentMessageRef = useRef<HTMLDivElement>(null);
  const cleanupRef = useRef<(() => void) | null>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Cleanup ao desmontar
  useEffect(() => {
    return () => {
      cleanupRef.current?.();
    };
  }, []);

  const sendMessage = (query: string) => {
    if (isStreaming) {
      console.warn('[Chat] Already streaming, ignoring request');
      return;
    }

    console.log('[Chat] Sending message:', query);

    // ✅ CRÍTICO: Limpar conexão anterior se existir
    if (cleanupRef.current) {
      console.log('[Chat] Cleaning up previous connection');
      cleanupRef.current();
      cleanupRef.current = null;
    }

    // Adicionar mensagem do usuário
    const userMessage: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      content: query,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, userMessage]);

    // Criar mensagem vazia para streaming
    const assistantId = crypto.randomUUID();
    const assistantMessage: Message = {
      id: assistantId,
      role: 'assistant',
      content: '',
      timestamp: new Date(),
      isStreaming: true,
    };
    setMessages((prev) => [...prev, assistantMessage]);

    setIsStreaming(true);
    let buffer = '';
    let lastUpdate = Date.now();

    // Obter token JWT do Zustand store
    const token = useAuthStore.getState().token;
    console.log('[Chat] Token from store:', token ? `${token.substring(0, 20)}... (${token.length} chars)` : 'NULL');
    
    if (!token) {
      console.error('[Chat] No token available');
      setMessages((prev) =>
        prev.map((msg) =>
          msg.id === assistantId
            ? {
                ...msg,
                content: '❌ Erro: Não autenticado. Faça login novamente.',
                isStreaming: false,
              }
            : msg
        )
      );
      setIsStreaming(false);
      return;
    }

    // ⚠️ TEMPORÁRIO: Usar POST ao invés de SSE (SSE com crash)
    console.log('[Chat] Using POST method (SSE disabled temporarily)');

    fetch('/api/v1/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      body: JSON.stringify({ query }),
    })
      .then(res => res.json())
      .then(data => {
        setMessages((prev) =>
          prev.map((msg) =>
            msg.id === assistantId
              ? { ...msg, content: data.response || 'Sem resposta', isStreaming: false }
              : msg
          )
        );
        setIsStreaming(false);
      })
      .catch(error => {
        console.error('[Chat] Error:', error);
        setMessages((prev) =>
          prev.map((msg) =>
            msg.id === assistantId
              ? { ...msg, content: `❌ Erro: ${error.message}`, isStreaming: false }
              : msg
          )
        );
        setIsStreaming(false);
      });

    return; // Skip SSE code below

    const cleanup = createSSEConnection(
      '', // Disabled
      {
        onMessage: (data) => {
          buffer += data.text;

          // Atualizar DOM diretamente (performance)
          const now = Date.now();
          if (now - lastUpdate > 50) {
            // Throttle: 50ms
            if (currentMessageRef.current) {
              currentMessageRef.current.textContent = buffer;
            }
            lastUpdate = now;
          }
        },
        onComplete: () => {
          console.log('[Chat] Stream completed');
          // Sincronizar com React state
          setMessages((prev) =>
            prev.map((msg) =>
              msg.id === assistantId
                ? { ...msg, content: buffer, isStreaming: false }
                : msg
            )
          );
          setIsStreaming(false);
          cleanupRef.current = null;
        },
        onError: (error) => {
          console.error('[Chat] SSE Error:', error);
          setMessages((prev) =>
            prev.map((msg) =>
              msg.id === assistantId
                ? {
                    ...msg,
                    content: `❌ Erro: ${error.message}`,
                    isStreaming: false,
                  }
                : msg
            )
          );
          setIsStreaming(false);
          cleanupRef.current = null;
        },
      }
    );

    cleanupRef.current = cleanup;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isStreaming) return;

    sendMessage(input.trim());
    setInput('');
  };

  return (
    <div className="flex h-[calc(100vh-4rem)] flex-col space-y-4">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Chat BI com IA</h1>
        <p className="text-muted-foreground">
          Faça perguntas sobre seus dados em linguagem natural
        </p>
      </div>

      {/* Messages area */}
      <Card className="flex-1 overflow-y-auto p-4">
        <div className="space-y-4">
          {messages.length === 0 ? (
            <div className="flex h-full items-center justify-center text-center">
              <div className="space-y-2">
                <p className="text-lg font-medium">
                  Bem-vindo ao Chat BI! 👋
                </p>
                <p className="text-sm text-muted-foreground">
                  Comece fazendo uma pergunta sobre seus dados
                </p>
              </div>
            </div>
          ) : (
            messages.map((message) => (
              <ChatMessage
                key={message.id}
                message={message}
                messageRef={
                  message.isStreaming ? currentMessageRef : undefined
                }
              />
            ))
          )}
          <div ref={messagesEndRef} />
        </div>
      </Card>

      {/* Indicador de streaming */}
      {isStreaming && (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          <span>IA está digitando...</span>
        </div>
      )}

      {/* Input area */}
      <form onSubmit={handleSubmit} className="flex gap-2">
        <Input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Digite sua pergunta sobre os dados..."
          disabled={isStreaming}
          className="flex-1"
        />
        <Button
          type="submit"
          disabled={isStreaming || !input.trim()}
          size="icon"
        >
          {isStreaming ? (
            <Loader2 className="h-5 w-5 animate-spin" />
          ) : (
            <Send className="h-5 w-5" />
          )}
        </Button>
      </form>
    </div>
  );
}

// frontend-solid/src/pages/Chat.tsx
import { createSignal, createEffect, onCleanup, For } from 'solid-js';
import auth from '@/store/auth';

// Interface para mensagem
interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  text: string;
  timestamp: number;
}

export default function Chat() {
  const [messages, setMessages] = createSignal<Message[]>([
    { id: '0', role: 'assistant', text: 'Olá! Sou seu assistente de BI. Pergunte sobre vendas, produtos ou estoque.', timestamp: Date.now() }
  ]);
  const [input, setInput] = createSignal('');
  const [isStreaming, setIsStreaming] = createSignal(false);
  let messagesEndRef: HTMLDivElement | undefined;

  // Auto-scroll
  createEffect(() => {
    messages();
    if (messagesEndRef) {
      messagesEndRef.scrollIntoView({ behavior: 'smooth' });
    }
  });

  const sendMessage = async (e: Event) => {
    e.preventDefault();
    if (!input() || isStreaming()) return;

    const userText = input();
    setInput('');
    
    // Validar autenticação
    const token = auth.token();
    if (!token) {
      console.error('❌ Token não encontrado');
      const errorMsg: Message = { 
        id: Date.now().toString(), 
        role: 'assistant', 
        text: '[Erro: Você não está autenticado. Por favor, faça login novamente.]', 
        timestamp: Date.now() 
      };
      setMessages(prev => [...prev, errorMsg]);
      return;
    }
    
    // Adiciona mensagem do usuário
    const userMsg: Message = { id: Date.now().toString(), role: 'user', text: userText, timestamp: Date.now() };
    setMessages(prev => [...prev, userMsg]);
    setIsStreaming(true);

    // Prepara mensagem do assistente
    const assistantId = (Date.now() + 1).toString();
    setMessages(prev => [...prev, { id: assistantId, role: 'assistant', text: '', timestamp: Date.now() }]);

    try {
      // Conexão SSE Real com Backend
      console.log('📡 Iniciando SSE com token:', token.substring(0, 20) + '...');
      const eventSource = new EventSource(`/api/v1/chat/stream?q=${encodeURIComponent(userText)}&token=${token}`);

      eventSource.onmessage = (event) => {
        try {
          const data = JSON.parse(event.data);
          
          if (data.done) {
            console.log('✅ Stream concluído');
            eventSource.close();
            setIsStreaming(false);
            return;
          }

          if (data.text) {
            setMessages(prev => prev.map(msg => 
              msg.id === assistantId ? { ...msg, text: msg.text + data.text } : msg
            ));
          }
          
          if (data.error) {
            console.error('❌ Erro do servidor:', data.error);
            setMessages(prev => prev.map(msg => 
              msg.id === assistantId ? { ...msg, text: msg.text + "\n[Erro: " + data.error + "]" } : msg
            ));
            eventSource.close();
            setIsStreaming(false);
          }

        } catch (err) {
          console.error("❌ SSE Parse Error", err);
        }
      };

      eventSource.onerror = (err) => {
        console.error("❌ EventSource failed:", err);
        eventSource.close();
        setIsStreaming(false);
        setMessages(prev => prev.map(msg => 
           msg.id === assistantId ? { ...msg, text: msg.text + "\n⚠️ Erro de conexão com o servidor." } : msg
        ));
      };

    } catch (err) {
      console.error("❌ Chat error:", err);
      setIsStreaming(false);
      setMessages(prev => prev.map(msg => 
        msg.id === assistantId ? { ...msg, text: "\n❌ Erro ao processar mensagem." } : msg
      ));
    }
  };

  return (
    <div class="flex flex-col h-full max-w-4xl mx-auto">
      <div class="flex-1 overflow-y-auto p-6 space-y-6">
        <For each={messages()}>
          {(msg) => (
            <div class={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div 
                class={`max-w-[80%] rounded-lg p-4 text-sm leading-relaxed shadow-sm ${ 
                  msg.role === 'user' 
                    ? 'bg-primary text-primary-foreground' 
                    : 'bg-card border text-card-foreground'
                }`}
                style={{"white-space": "pre-wrap"}} 
              >
                {msg.text}
                {msg.role === 'assistant' && isStreaming() && msg.id === messages()[messages().length - 1].id && (
                   <span class="inline-block w-2 h-4 ml-1 bg-current animate-pulse">|</span>
                )}
              </div>
            </div>
          )}
        </For>
        <div ref={messagesEndRef} />
      </div>

      <div class="p-4 border-t bg-background/50 backdrop-blur">
        <form onSubmit={sendMessage} class="flex gap-2">
          <input
            type="text"
            class="input flex-1"
            value={input()}
            onInput={(e) => setInput(e.currentTarget.value)}
            placeholder="Faça uma pergunta sobre os dados..."
            disabled={isStreaming()}
          />
          <button type="submit" class="btn btn-primary" disabled={isStreaming() || !input()}>
            Enviar
          </button>
        </form>
      </div>
    </div>
  );
}
